### ISSUE TITLE
As a developer new to EF Core, I need to understand if the tutorial is useful for me.

### ISSUE THREAD

**Issue by rdahlman3** [LadyNaggaga/training-tutorials#1]
Content is done, needs to be reviewed and put into the correct format with markdown.

**Comment by rdahlman3** [comment]
https://trello.com/c/2l2yResf/2-as-a-user-i-need-to-know-how-to-get-started-with-entity-framework-core

**Comment by arynhuck** [comment]
This issue was closed with pull request #19
