### ISSUE TITLE
As a developer new to EF Core, I need to understand how to generate databases and data models.

### ISSUE THREAD

**Issue by rdahlman3** [LadyNaggaga/training-tutorials#2]
~~https://trello.com/c/YWycu7F3/3-as-a-user-i-need-to-understand-how-to-add-ef-core-to-a-project~~

~~See:
https://trello.com/c/1GKoGY8P/21-as-a-user-i-need-to-know-how-to-connect-my-ef-core-project-to-a-database~~

https://trello.com/c/TLQUsHwF/12-8-as-a-developer-new-to-ef-core-i-need-to-understand-how-to-generate-databases-and-data-models

**Comment by rdahlman3** [comment]
https://trello.com/c/YWycu7F3/3-as-a-user-i-need-to-understand-how-to-add-ef-core-to-a-project

**Comment by arynhuck** [comment]
I'm fixing how we think of this issue right now, so for now this should not be bothered with.

The branch that contains some relevant content will still be used, but this issue has been split into 2. See issue #23 for the other half.
