### ISSUE TITLE
As a developer new to EF Core, I want to know which database providers are supported by EF Core in the Intro to EF Core lesson so I can decide if it is the right tool for me.

### ISSUE THREAD

**Issue by helmoski** [LadyNaggaga/training-tutorials#22]
Update Intro to EF Core lesson to explain how EF Core supports several database providers and link to the database providers page of the docs.

**Comment by arynhuck** [comment]
Markdown created. Let's make a branch for this!

**Comment by arynhuck** [comment]
See trello board: https://trello.com/c/pLJF5Cfo/20-0-as-a-developer-new-to-ef-core-i-want-to-know-which-database-providers-are-supported-by-ef-core-in-the-intro-to-ef-core-lesson-
