### ISSUE TITLE
Update Installing EF Core

### ISSUE THREAD

**Issue by rdahlman3** [LadyNaggaga/training-tutorials#25]
- [x] Under Install .NET Core, change to "First, you will need to install..."
- [x] Under Create New Project, remove the "you can" in the parentheses
- [x] Change the second "you need" to "you must" under Add EF Core to Project

**Comment by arynhuck** [comment]
See PR #93

**Comment by arynhuck** [comment]
@rdahlman3, hey look. I did it.

**Comment by rdahlman3** [comment]
proud of you
