### ISSUE TITLE
Small Wording Changes

### ISSUE THREAD

**Issue by arynhuck** [LadyNaggaga/training-tutorials#88]
This issue changes words in the tutorial based on user feedback.

- [x] Getting Started: eliminate redundancy
- [x] Intro to EF Core: eliminate redundancy
- [x] Intro to EF Core: formatting articles names correctly
- [x] Intro to EF Core: standardizing hyperlinks
- [x] Installing EF Core: fix "you don't need to do this" sentence to emphasize the fact it's optional
- [x] Installing EF Core: format .NET Core page reference correctly
- [x] Installing EF Core: specify commands are run in command line
- [x] Installing EF Core: get rid of those # in code examples
- [x] Installing EF Core: small wording and formatting
- [x] Understanding Models: standardize vocab formatting
- [x] Understanding Models: minor wording changes and who are readers?
- [x] Understanding Models: capitalize words in POCO
- [x] Querying Data: wording and grammar
- [x] Querying Data: fix consistency of ()
- [x] Loading Related Data: wording
- [x] Loading Related Data: vocab formatting consistency
- [x] Loading Related Data: aggregate functions as words or `code` words
- [x] Manipulating Entities: capitalize words in CRUD
- [x] Manipulating Entities: standardize vocab

**Comment by deakgeek** [comment]
There's a change in Installing EF Core that also needs to be changed. The reference to the .NET Core page includes "page" in the hyperlink text. This should not be the case.
